CREATE OR REPLACE VIEW DEMO_DB.DATA_PIPELINE.DEPARTMENT_SALARY_AVG AS
SELECT 
  D.DEPARTMENT_NAME,
  ROUND(AVG(E.SALARY), 2) AS AVG_SALARY
FROM DEMO_DB.DATA_PIPELINE.EMPLOYEES E
JOIN DEMO_DB.DATA_PIPELINE.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;
