CREATE OR REPLACE VIEW DEMO_DB.DATA_PIPELINE.EMPLOYEE_PROJECT_SUMMARY AS
SELECT 
  E.EMPLOYEE_NAME,
  P.PROJECT_NAME,
  T.WORK_DATE,
  T.HOURS_WORKED
FROM DEMO_DB.DATA_PIPELINE.EMPLOYEES E
JOIN DEMO_DB.DATA_PIPELINE.TIMESHEETS T ON E.EMPLOYEE_ID = T.EMPLOYEE_ID
JOIN DEMO_DB.DATA_PIPELINE.PROJECTS P ON T.PROJECT_ID = P.PROJECT_ID;
