USE DATABASE DEMO_DB;

CREATE SCHEMA IF NOT EXISTS DATA_PIPELINE;

CREATE TABLE IF NOT EXISTS DATA_PIPELINE.raw_data (
    id INT,
    data NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DATA_PIPELINE.processed_data (
    id INT,
    transformed_data VARIANT,
    processed_at TIMESTAMP
);
