create or replace TABLE DEPARTMENTS (
	DEPARTMENT_ID NUMBER(38,0) NOT NULL,
	DEPARTMENT_NAME VARCHAR(16777216),
	primary key (DEPARTMENT_ID)
);;

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (101, 'Engineering');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (102, 'Marketing');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES (103, 'Human Resources');
