CREATE OR REPLACE TABLE DEMO_DB.DATA_PIPELINE.DEPARTMENTS (
  DEPARTMENT_ID NUMBER(38,0) PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR(100)
);

INSERT INTO DEMO_DB.DATA_PIPELINE.DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(1, 'Engineering'),
(2, 'Marketing'),
(3, 'Finance'),
(4, 'Human Resources');
