create or replace TABLE EMPLOYEES (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	DEPARTMENT_ID NUMBER(38,0),
	HIRE_DATE DATE,
	primary key (EMPLOYEE_ID),
	constraint FK_DEPARTMENT foreign key (DEPARTMENT_ID) references DEMO_DB.DATA_PIPELINE.DEPARTMENTS(DEPARTMENT_ID)
);;

