create or replace TABLE EMPLOYEES (
	EMPLOYEE_ID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(16777216),
	EMAIL VARCHAR(16777216),
	DEPARTMENT_ID NUMBER(38,0),
	HIRE_DATE DATE,
	primary key (EMPLOYEE_ID)
);;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, NAME, EMAIL, DEPARTMENT_ID, HIRE_DATE) VALUES (1, 'Alice Johnson', 'alice.johnson@example.com', 101, 2021-03-01);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, NAME, EMAIL, DEPARTMENT_ID, HIRE_DATE) VALUES (2, 'Bob Smith', 'bob.smith@example.com', 102, 2022-07-15);
INSERT INTO EMPLOYEES (EMPLOYEE_ID, NAME, EMAIL, DEPARTMENT_ID, HIRE_DATE) VALUES (3, 'Charlie Lee', 'charlie.lee@example.com', 101, 2020-11-22);
