CREATE OR REPLACE TABLE DEMO_DB.DATA_PIPELINE.EMPLOYEES (
  EMPLOYEE_ID NUMBER(38,0) PRIMARY KEY,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  DEPARTMENT_ID NUMBER(38,0),
  JOIN_DATE DATE,
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEMO_DB.DATA_PIPELINE.DEPARTMENTS(DEPARTMENT_ID)
);

INSERT INTO DEMO_DB.DATA_PIPELINE.EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, JOIN_DATE) VALUES
(101, 'Alice', 'Smith', 1, TO_DATE('2022-01-01','YYYY-MM-DD')),
(102, 'Bob', 'Johnson', 2, TO_DATE('2021-06-15','YYYY-MM-DD')),
(103, 'Carol', 'Davis', 1, TO_DATE('2020-03-20','YYYY-MM-DD')),
(104, 'David', 'Brown', 3, TO_DATE('2019-11-10','YYYY-MM-DD')),
(105, 'Eva', 'Miller', 4, TO_DATE('2023-02-01','YYYY-MM-DD'));
