create or replace TABLE PRODUCTS (
	PRODUCTID NUMBER(38,0) NOT NULL,
	PRODUCTNAME VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	PRICE NUMBER(10,2),
	STOCK NUMBER(38,0),
	primary key (PRODUCTID)
);;

INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (100, 'Laptop', 'Electronics', 899.99, 20);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (101, 'Headphones', 'Electronics', 49.99, 100);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (102, 'Office Chair', 'Furniture', 149.99, 50);
