create or replace TABLE PRODUCTS (
	PRODUCTID NUMBER(38,0) NOT NULL,
	PRODUCTNAME VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	PRICE NUMBER(10,2),
	STOCK NUMBER(38,0),
	primary key (PRODUCTID)
);;

INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (100, 'Laptop', 'Electronics', 899.99, 20);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (101, 'Headphones', 'Electronics', 49.99, 100);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (102, 'Office Chair', 'Furniture', 149.99, 50);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (103, 'Microwave', 'Appliances', 99.99, 20);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (104, 'Toaster', 'Appliances', 29.99, 50);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (105, 'Coffee Table', 'Furniture', 199.99, 30);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (106, 'Bookshelf', 'Furniture', 79.99, 20);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (107, 'Desk Lamp', 'Lighting', 19.99, 50);
INSERT INTO PRODUCTS (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCK) VALUES (108, 'Standing Desk', 'Furniture', 249.99, 20);
