create or replace TABLE SALARIES (
	EMPLOYEE_ID NUMBER(38,0),
	BASE_SALARY NUMBER(12,2),
	BONUS NUMBER(12,2),
	EFFECTIVE_DATE DATE,
	constraint FK_EMPLOYEE foreign key (EMPLOYEE_ID) references DEMO_DB.DATA_PIPELINE.EMPLOYEES(EMPLOYEE_ID)
);;

