CREATE OR REPLACE TABLE DEMO_DB.DATA_PIPELINE.SALARY_HISTORY (
  ENTRY_ID NUMBER(38,0) PRIMARY KEY,
  EMPLOYEE_ID NUMBER(38,0),
  CHANGE_DATE DATE,
  OLD_SALARY NUMBER(18,2),
  NEW_SALARY NUMBER(18,2),
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES DEMO_DB.DATA_PIPELINE.EMPLOYEES(EMPLOYEE_ID)
);