name: Auto Tag on Push to Main

on:
  push:
    branches:
      - main  # Trigger only on main branch pushes

permissions:
  contents: write  # Required to push tags to the repository

jobs:
  tag-latest-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 👈 IMPORTANT: Ensure full git history so tags are reachable

    - name: Set up Git config
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    - name: Generate timestamp-based tag and push
      run: |
        TAG="LastCommit-$(date +'%Y-%m-%d-%H%M%S')"
        echo "Generated tag: $TAG"

        # Prevent duplicate tagging
        if git tag | grep -q "^$TAG$"; then
          echo "⚠️ Tag $TAG already exists, skipping..."
          exit 0
        fi

        # Create annotated tag and push
        git tag -a "$TAG" -m "Automated tag for $TAG"
        git push origin "$TAG"
